version: 2.1

commands:
  pre_commands:
    parameters:
      node-version:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - |
              node-modules-{{ arch }}-<< parameters.node-version >>-{{ checksum "package-lock.json" }}
      - node/install:
          node-version: << parameters.node-version >>
      - node/install-packages
      - save_cache:
          key: |
            node-modules-{{ arch }}-<< parameters.node-version >>-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
          when: always

  post_commands:
    steps:
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports

orbs:
  node: circleci/node@2

jobs:
  test:
    parameters:
      node-version:
        type: string
    executor: node/default
    steps:
      - pre_commands:
          node-version: << parameters.node-version >>
      - run: npm test
      - post_commands

  lint:
    executor: node/default
    steps:
      - pre_commands:
          node-version: '12.17.0'
      - run: npm run lint
      - post_commands

  release:
    executor: node/default
    steps:
      - pre_commands:
          node-version: '12.17.0'
      - deploy:
          command: |
            echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ./.npmrc
            npm whoami
            npm run semantic-release
      - post_commands

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test:
          matrix:
            parameters:
              node-version:
                - '12.17.0'
      - release:
          context: semantic-release
          filters:
            branches:
              only: master
          requires:
            - lint
            - test
